// styles.ts
import {Dimensions, StyleSheet} from 'react-native';
import {colors} from './theme';
const {width, height} = Dimensions.get('window');

const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 1,
  },
  loaderContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  /* SigninScreen */
  gradientBackgroundd: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    position: 'relative',
  },

  signinInnerContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    zIndex: 2,
  },

  bottomGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '50%',
    zIndex: 1,
  },

  logo: {
    width: width * 0.2,
    height: width * 0.2,
    borderRadius: (width * 0.2) / 2,
    marginBottom: height * 0.06,
    marginTop: -height * 0.06,
  },

  title: {
    fontFamily: 'CalSans-Regular',
    fontSize: 28,
    color: '#000000',
    marginBottom: 20,
  },
  input: {
    width: '100%',
    height: 45,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 7,
    paddingHorizontal: 15,
    fontSize: 16,
    marginBottom: 15,
    backgroundColor: '#F2F2F2',
    color: '#000',
  },
  passwordContainer: {
    width: '100%',
    height: 45,
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 7,
    backgroundColor: '#F2F2F2',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 15,
    position: 'relative',
  },
  passwordInput: {
    flex: 1,
    fontSize: 16,
    height: '100%',
    paddingRight: 40,
    color: '#000',
  },
  eyeIconContainer: {
    position: 'absolute',
    right: 15,
    height: '100%',
    width: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  forgotPassword: {
    alignSelf: 'flex-end',
    marginBottom: 20,
    marginRight: 5,
    color: '#000000',
    fontFamily: 'CalSans-Regular',
    fontSize: 14,
  },
  button: {
    backgroundColor: '#E3EFFB',
    paddingVertical: 8,
    width: '40%',
    borderRadius: 10,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: {width: 0, height: 2},
    elevation: 3,
  },
  buttonText: {
    color: '#0E2B43',
    fontFamily: 'CalSans-Regular',
    fontSize: 16,
  },
  errorText: {
    color: 'red',
    fontSize: 14,
    marginTop: 5,
    alignSelf: 'flex-start',
    marginLeft: 5,
  },

  /* Homescreen */
  scrollContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  innerContainer: {
    padding: 20,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flatHeaderText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#0E2B40',
    fontFamily: 'CalSans-Regular',
  },
  greetingText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#0E2B40',
    fontFamily: 'CalSans-Regular',
  },
  dividerLine: {
    height: 1,
    width: '200%',
    backgroundColor: '#ccc',
    marginVertical: 8,
  },
  profileContainer: {
    alignItems: 'center',
  },
  profileImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  profileLabel: {
    fontSize: 12,
    color: '#0E2B40',
    fontWeight: '600',
    marginTop: 4,
    fontFamily: 'CalSans-Regular',
  },
  reminderBox: {
    borderWidth: 1,
    borderColor: '#454545',
    borderRadius: 12,
    marginTop: 20,
    padding: 15,
  },
  reminderRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  reminderIcon: {
    marginRight: 10,
  },
  reminderText: {
    fontSize: 14,
    color: '#758694',
    fontFamily: 'CalSans-Regular',
  },
  reminderDivider: {
    height: 1,
    backgroundColor: '#cdcdcd',
    marginVertical: 8,
  },
  sosContainerWrapper: {
    marginTop: 10,
    paddingHorizontal: 3,
  },
  sosArrowButton: {
    alignSelf: 'flex-end',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#D9D9D9',
    borderTopLeftRadius: 15,
    borderBottomLeftRadius: 15,
    padding: 8,
    borderWidth: 1,
    borderColor: '#A0A0A0',
    marginRight: 0,
    marginTop: 10,
    zIndex: 10,
    elevation: 5,
  },
  arrowCircle: {
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 50,
    padding: 6,
    backgroundColor: '#FFF',
    marginRight: 5,
  },
  hexagon: {
    width: 40,
    height: 23,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: -5,
    marginRight: -10,
  },
  hexagonInner: {
    width: 40,
    backgroundColor: '#F22E2E',
    height: 23,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hexagonBefore: {
    position: 'absolute',
    top: -11,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: 20,
    borderRightWidth: 20,
    borderBottomWidth: 11,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#F22E2E',
  },
  hexagonAfter: {
    position: 'absolute',
    bottom: -11,
    width: 0,
    height: 0,
    borderStyle: 'solid',
    borderLeftWidth: 20,
    borderRightWidth: 20,
    borderTopWidth: 11,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#F22E2E',
  },
  hexagonText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontFamily: 'CalSans-Regular',
  },
  menuColumnWrapper: {
    justifyContent: 'space-between',
    marginTop: 20,
  },
  menuCard: {
    width: (width - 80) / 3,
    height: 160,
    backgroundColor: '#f9f9f9',
    borderRadius: 12,
    padding: 12,
    justifyContent: 'space-between',
    borderBottomWidth: 4,
    borderBottomColor: '#115d93',
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 4,
    marginBottom: 15,
  },
  menuId: {
    position: 'absolute',
    right: 10,
    fontSize: 28,
    fontFamily: 'CalSans-Regular',
    color: '#0E2B43',
  },
  menuIcon: {
    width: 35,
    height: 35,
    alignSelf: 'flex-start',
    marginTop: 5,
  },
  menuTitle: {
    fontSize: 13,
    color: '#246898',
    fontWeight: '600',
    marginTop: 10,
    fontFamily: 'CalSans-Regular',
  },
  /* EditProfile Screen */
  snackbarContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  profileSection: {
    alignItems: 'center',
    backgroundColor: '#C0E1F7',
    height: '35%',
    borderRadius: 10,
    borderTopStartRadius: 0,
    borderTopEndRadius: 0,
    justifyContent: 'center',
  },
  editprofileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 3,
    borderColor: 'white',
  },
  editProfileText: {
    color: '#0E2B43',
    marginTop: 5,
    fontSize: 16,
    fontWeight: 'bold',
  },
  infoCard: {
    borderRadius: 12,
    position: 'absolute',
    top: '30%',
    left: '5%',
    width: '90%',
    display: 'flex',
    flexDirection: 'column',
    rowGap: 10,
    shadowColor: '#4A708BC2',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 8,
  },
  gradientBackground: {
    flex: 1,
    padding: 16,
    borderRadius: 12,
    paddingTop: 40,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#C2B7B7c6',
  },
  label: {
    color: '#0E2B43',
    fontSize: 16,
    fontWeight: '500',
  },
  value: {
    color: '#0E2B43',
    fontSize: 16,
  },
  editpasswordContainer: {
    flexDirection: 'column',
    rowGap: 5,
  },
  changePasswordText: {
    color: '#124E78',
    fontSize: 10,
    fontStyle: 'italic',
  },
  sectionHeader: {
    color: '#0E2B43',
    marginVertical: 10,
    zIndex: 10,
  },
  gradientHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 7,
    width: '100%',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
  },
  sectionTitle: {
    color: '#0E2B43',
    fontSize: 16,
    fontWeight: 'bold',
  },
  contactDetails: {
    marginTop: -18,
    backgroundColor: '#CDE7F8',
    borderRadius: 8,
    padding: 4,
    paddingTop: 22,
  },
  contactRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#a1a1a1',
  },
  contactLabel: {
    color: '#0E2B43',
    fontSize: 14,
    fontWeight: '600',
  },
  contactValue: {
    color: '#0E2B43',
    fontSize: 14,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  inputField: {
    backgroundColor: '#CDE7F8 ',
    borderRadius: 8,
    padding: 10,
    color: 'black',
    fontSize: 14,
    marginTop: 5,
  },
  logoutButtonContainer: {
    padding: 20,
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  logoutButton: {
    backgroundColor: '#FF0000',
    paddingVertical: 10,
    paddingHorizontal: 40,
    borderRadius: 8,
  },
  logoutButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  alertOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 99,
  },
  alertBox: {
    backgroundColor: '#fefaf6',
    width: '80%',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    elevation: 8,
  },
  alertText: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 20,
    textAlign: 'center',
    color: '#333',
  },
  alertActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  stayButton: {
    flex: 1,
    backgroundColor: '#D9D9D9',
    paddingVertical: 10,
    borderRadius: 6,
    marginRight: 10,
    alignItems: 'center',
  },
  stayButtonText: {
    color: '#333',
    fontWeight: 'bold',
  },
  confirmLogoutButton: {
    flex: 1,
    backgroundColor: '#19B244',
    paddingVertical: 10,
    borderRadius: 6,
    marginLeft: 10,
    alignItems: 'center',
  },
  confirmLogoutText: {
    color: '#fff',
    fontWeight: 'bold',
  },

  /* ProfileViewScreen */
  visitorCardWrapper: {
    backgroundColor: '#C0E1F7',
    padding: 16,
    borderRadius: 8,
    marginBottom: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerText: {
    fontSize: 20,
    fontFamily: 'CalSans-Regular',
    color: '#0E2B43',
  },
  divider: {
    width: '80%',
    height: 1,
    backgroundColor: '#A5B1BC',
    marginVertical: 8,
    zIndex: 1,
  },
  divider1: {
    width: '80%',
    height: 1,
    backgroundColor: '#9F9F9F',
    marginVertical: 8,
    zIndex: 1,
  },
  visitorCard: {
    flexDirection: 'row',
    height: '20%',
    justifyContent: 'space-between',
    backgroundColor: '#FFFFFF',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
  },
  visitorName: {
    color: '#0E2B43',
    fontSize: 16,
    fontFamily: 'CalSans-Regular',
  },
  iconContainer: {
    flexDirection: 'row',
    gap: 10,
  },
  iconCircleOutline: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#000000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconCircleFilled: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#19B244',
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoTitle: {
    fontSize: 20,
    fontFamily: 'CalSans-Regular',
    color: '#0E2B43',
    textAlign: 'center',
    marginVertical: 10,
  },
  visitorImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: 'black',
  },
  logsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 8,
    position: 'relative',
  },
  logsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  expandIcon: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#CDE7F8',
    borderRadius: 8,
    padding: 5,
    borderWidth: 1,
    borderColor: '#FFFFFF',
  },

  logsTitle: {
    fontSize: 18,
    fontFamily: 'CalSans-Regular',
    color: '#0A273F',
  },
  logItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 15,
  },
  logText: {
    flex: 1,
    textAlign: 'center',
    fontFamily: 'ChesnaGrotesk-MediumItalic',
    color: '#3B5366',
  },
  rowDivider: {
    height: 1,
    backgroundColor: '#9F9F9F',
    marginHorizontal: 10,
  },
  noVisitorsText: {
    textAlign: 'center',
    fontFamily: 'CalSans-Regular',
    color: '#FFFFFF',
    paddingVertical: 10,
  },
  scanText: {
    textAlign: 'center',
    color: '#0E2B43',
    fontSize: 14,
    fontFamily: 'ChesnaGrotesk-MediumItalic',
    marginTop: 5,
    textDecorationLine: 'underline',
  },

  /* AddVisitorScreen */
  headerImage: {
    width: '100%',
    height: 80,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#000000',
    marginTop: '10%',
    marginHorizontal: 16,
    padding: 0,
    alignSelf: 'center',
    width: '90%',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: 10,
  },
  cardTitle: {
    fontSize: 18,
    fontFamily: 'CalSans-Regular',
    color: '#0E2B43',
  },
  addIconContainer: {
    width: 20,
    height: 20,
    borderRadius: 20,
    backgroundColor: '#0E2B43',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 2, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 3,
    elevation: 5,
  },
  inputBox: {
    width: '100%',
    backgroundColor: '#D9EBFB',
    borderRadius: 8,
    padding: 10,
    alignSelf: 'center',
    overflow: 'hidden',
  },
  AddvisitorCard: {
    borderRadius: 8,
    backgroundColor: '#D9EBFB',
    overflow: 'hidden',
    marginTop: 40,
    minHeight: 70,
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignSelf: 'center',
    width: '100%',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  AddVisitorlabel: {
    fontSize: 16,
    fontFamily: 'CalSans-Regular',
    color: '#0E2B43',
    flex: 0.3,
  },
  AddVisitorinput: {
    fontSize: 14,
    fontFamily: 'CalSans-Regular',
    flex: 0.7,
    borderBottomWidth: 1,
    borderBottomColor: '#88C8F1',
    color: '#000000',
    paddingVertical: 5,
  },
  dateInput: {
    flex: 0.7,
    borderBottomWidth: 1,
    borderBottomColor: '#88C8F1',
    paddingVertical: 5,
  },
  dateText: {
    fontSize: 14,
    fontFamily: 'CalSans-Regular',
  },
  dropdownContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    marginBottom: 10,
  },
  dropdownLabel: {
    fontSize: 16,
    fontFamily: 'CalSans-Regular',
    color: '#0E2B43',
    flex: 0.3,
  },
  dropdown: {
    flex: 0.7,
    borderWidth: 1,
    borderColor: '#88C8F1',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#F8F9FA',
  },
  dropdownText: {
    fontSize: 14,
    fontFamily: 'CalSans-Regular',
  },
  AddvisitorName: {
    color: '#0E2B43',
    fontSize: 20,
    fontFamily: 'CalSans-Regular',
  },
  visitorDate: {
    color: '#0E2B43',
    fontSize: 15,
    fontFamily: 'CalSans-Regular',
    textAlign: 'right',
  },
  buttonWrapper: {
    borderRadius: 8,
    overflow: 'hidden',
    marginTop: 20,
  },
  addButton: {
    backgroundColor: '#D9EBFB',
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  addButtonText: {
    color: '#0E2B43',
    fontSize: 18,
    fontFamily: 'CalSans-Regular',
  },

  /* NotificationScreen */
  Notificationheader: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#154365',
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  notificationIcon: {
    width: 24,
    height: 24,
    tintColor: '#134E78',
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#706E6E4D',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#000000',
    padding: 2,
    marginVertical: 2,
  },
  tabButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 5,
    borderRadius: 10,
  },
  activeTab: {
    backgroundColor: '#0E2B43',
  },
  tabText: {
    fontSize: 16,
    color: '#0E2B43',
    fontWeight: 'bold',
  },
  activeTabText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  list: {
    marginHorizontal: -8,
  },
  notificationContainer: {
    height: 'auto',
  },
  dateBadge: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 15,
    marginVertical: 7,
    marginTop: 17,
  },
  NotificationdateText: {
    fontSize: 18,
    color: '#0E2B43',
    fontWeight: 'bold',
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    marginLeft: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },

  badgeText: {
    color: 'white',
    fontWeight: 'bold',
  },
  Notificationcard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#C0E1F7',
    borderRadius: 10,
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: '#000000',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 4,
    marginVertical: 6,
  },

  icon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 15,
  },
  textContainer: {
    flex: 1,
  },
  userText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#0E2B43',
  },
  messageText: {
    fontWeight: 'normal',
    color: '#555151',
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 10,
  },

  ignoreButton: {
    backgroundColor: '#444444',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#2B2B2B',
    marginRight: 10,
  },

  readButton: {
    backgroundColor: '#19B244',
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '#2B2B2B',
  },
  ignoreText: {
    color: '#FFFFFF',
  },
  readText: {
    color: '#FFFFFF',
  },
  card1: {
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#000000',
    backgroundColor: '#FFFFFF',
    margin: 10,
  },
  amenitiesTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#154365',
    marginHorizontal: 16,
    marginBottom: 10,
  },

  amenitiesContainer: {
    borderWidth: 1,
    borderColor: '#000000',
    borderStyle: 'dashed',
    borderRadius: 8,
    padding: 20,
    marginHorizontal: 16,
    backgroundColor: '#FFFFFF',
  },

  amenitiesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },

  amenityItem: {
    alignItems: 'center',
    width: 80,
  },

  amenityIcon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    marginBottom: 6,
  },

  amenityText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#0E2B43',
    textAlign: 'center',
  },

  seeAllButton: {
    marginLeft: 'auto',
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  seeAllText: {
    color: '#0E2B43',
    fontWeight: 'bold',
    fontSize: 16,
  },
  documentsTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#154365',
    margin: 5,
  },
  documentsContainer: {
    padding: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#000',
    borderStyle: 'dashed',
    marginTop: 20,
    backgroundColor: '#F9FBFD',
  },
  documentItem: {
    backgroundColor: '#B5DCFA',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginVertical: 5,
  },
  documentText: {
    color: '#000',
    fontWeight: 'bold',
    fontSize: 14,
    flex: 1,
  },
  downloadIcon: {
    width: 20,
    height: 20,
    tintColor: '#000',
    marginLeft: 10,
  },

  /* Booking Screen */
  bookingheaderContainer: {
    position: 'relative',
  },
  backButton: {
    position: 'absolute',
    top: 30,
    left: 20,
    width: 40,
    height: 40,
    zIndex: 10,
  },
  bookingheaderImage: {
    width: '100%',
    height: 70,
    resizeMode: 'cover',
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
  },
  bookinglabel: {
    color: '#0E2B43',
    fontWeight: 'bold',
    fontSize: 14,
  },
  inputWithButton: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#00000061',
    backgroundColor: '#88C8F1',
    borderRadius: 6,
    paddingHorizontal: 10,
    marginBottom: 10,
    marginTop: 8,
  },

  inputInside: {
    flex: 1,
    paddingVertical: 8,
    paddingRight: 10,
    color: '#000',
  },

  addDescriptionBtnInline: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#C0E1F7',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 4,
    marginLeft: 8,
  },
  addDescriptionText: {
    color: '#0E2B43',
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  amenityInfo: {
    fontSize: 12,
    color: '#444',
    marginBottom: 10,
  },
  bookingrow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timeDateBox: {
    flex: 1,
    marginRight: 8,
  },
  iconInput: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#00000061',
    backgroundColor: '#88C8F1',
    borderRadius: 6,
    padding: 10,
    marginBottom: 10,
  },
  bookingdropdown: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#00000061',
    backgroundColor: '#88C8F1',
    borderRadius: 6,
    padding: 10,
    marginBottom: 20,
  },
  bookindropdownText: {
    color: '#000',
  },
  bookingbuttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  bookBtn: {
    flex: 1,
    backgroundColor: '#154365',
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
    marginRight: 8,
  },
  bookBtnText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  resetBtn: {
    flex: 1,
    backgroundColor: '#C0E1F7',
    paddingVertical: 10,
    borderRadius: 6,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  resetBtnText: {
    color: '#0E2B43',
    fontWeight: 'bold',
    marginLeft: 6,
  },
  addEventBtn: {
    backgroundColor: '#88C8F1',
    padding: 12,
    borderRadius: 6,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  addEventText: {
    color: '#0E2B43',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },

  /* Sos Screen */
  Soscontainer: {
    flex: 1,
    backgroundColor: '#B00000',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  SosinputContainer: {
    width: '100%',
    marginBottom: 20,
  },
  infoContainer: {
    alignItems: 'center',
    marginTop: 10,
  },

  paperInput: {
    backgroundColor: '#FBECEC',
    borderRadius: 30,
    fontSize: 14,
  },
  sendIconWrapper: {
    backgroundColor: '#FFC0C0',
    borderRadius: 20,
    padding: 6,
    marginTop: 6,
    marginRight: 6,
  },

  SosbackButton: {
    position: 'absolute',
    top: 25,
    left: -10,
    zIndex: 10,
    transform: [{translateY: -25}],
    backgroundColor: '#D9D9D9',
    width: 50,
    height: 50,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#A0A0A0',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 3,
  },
  iconCircle: {
    borderWidth: 1,
    borderColor: '#000000',
    borderRadius: 50,
    padding: 6,
  },
  Soshexagon: {
    width: 100,
    height: 55,
    marginBottom: 30,
  },
  SoshexagonInner: {
    width: 100,
    height: 55,
    backgroundColor: '#ff0000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  SoshexagonBefore: {
    position: 'absolute',
    top: -25,
    left: 0,
    width: 0,
    height: 0,
    borderLeftWidth: 50,
    borderRightWidth: 50,
    borderBottomWidth: 25,
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#ff0000',
  },
  SoshexagonAfter: {
    position: 'absolute',
    bottom: -25,
    left: 0,
    width: 0,
    height: 0,
    borderLeftWidth: 50,
    borderRightWidth: 50,
    borderTopWidth: 25,
    borderStyle: 'solid',
    backgroundColor: 'transparent',
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#ff0000',
  },

  sosText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: 'white',
  },
  subText: {
    color: '#fff',
    fontSize: 16,
    marginBottom: 5,
    textAlign: 'center',
  },
});

export default globalStyles;
